spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinAutoConfiguration
    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
    - org.springframework.boot.actuate.autoconfigure.metrics.KafkaMetricsAutoConfiguration
    - org.springframework.boot.autoconfigure.batch.BatchAutoConfiguration
    - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration